const EmployeeActions = {
  SAVE_EMPLOYEE: "SAVE_EMPLOYEE",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  GET_EMPLOYEE: "GET_EMPLOYEE",
  GET_ALL_EMPLOYEES: "GET_ALL_EMPLOYEES",
  GET_EMPLOYEES_BY_FILTERS: "GET_EMPLOYEES_BY_FILTERS",
};
export default EmployeeActions;
